resolvebranch

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,8 +33,11 @@ jobs:
             git checkout -b production origin/production
           fi
 
-          git merge main --no-commit --no-ff  # Effectue la fusion sans commettre automatiquement
-          git restore --staged .github/workflows/  # Réinitialise les workflows pour ne pas les inclure dans le commit
+          # Fusionne main dans production sans commettre automatiquement
+          git merge main --no-commit --no-ff
+
+          # Réinitialise les workflows pour ne pas les inclure dans le commit
+          git restore --staged .github/workflows/  
 
           # Vérifier s'il y a des changements à commettre
           if git diff-index --quiet HEAD; then
@@ -42,10 +45,12 @@ jobs:
           else
             git commit -m "Merge main into production, excluding workflow changes"
             git push origin production  # Pousse la branche fusionnée
+          fi  # Fin de la vérification des changements
 
   build_and_push_images:
     needs: merge_to_production
     runs-on: ubuntu-latest
+    environment: production
 
     steps:
       - name: Checkout production branch
@@ -64,29 +69,39 @@ jobs:
 
       - name: Build and push Backend (Spring Boot) Docker image
         run: |
-          docker build -t chirack96/springboot-app:latest ./dev || { echo "Docker build failed"; exit 1; }
-          docker push chirack96/springboot-app:latest || { echo "Docker push failed"; exit 1; }
+          docker build -t ${{ env.DOCKER_USERNAME }}/springboot-app:latest ./dev || { echo "Docker build failed"; exit 1; }
+          docker push ${{ env.DOCKER_USERNAME }}/springboot-app:latest || { echo "Docker push failed"; exit 1; }
 
       - name: Build and push Frontend (Angular) Docker image
         run: |
-          docker build -t chirack96/angular-app:latest ./Frontend || { echo "Docker build failed"; exit 1; }
-          docker push chirack96/angular-app:latest || { echo "Docker push failed"; exit 1; }
+          docker build -t ${{ env.DOCKER_USERNAME }}/angular-app:latest ./Frontend || { echo "Docker build failed"; exit 1; }
+          docker push ${{ env.DOCKER_USERNAME }}/angular-app:latest || { echo "Docker push failed"; exit 1; }
 
       - name: Clean up Docker images
         run: |
-          docker image prune -f
+          docker image prune -f  # Nettoie les images Docker non utilisées
 
   deploy_to_server:
     needs: build_and_push_images
     runs-on: ubuntu-latest
+    environment: production
     steps:
       - name: Deploy to local server via SSH
         uses: appleboy/ssh-action@v0.1.3
         with:
+          debug: true
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           password: ${{ secrets.SERVER_PASSWORD }}
+          port: 32770  # Port externe redirigé vers le port 22
           script: |
             cd C:/Users/chira/Documents/Pro/Mon_CRM
-            docker-compose pull
-            docker-compose up -d
+            docker-compose pull  # Récupère les nouvelles images Docker
+            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
+            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
+            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
+            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
+            MYSQL_USER=${{ secrets.MYSQL_USER }} \
+            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
+            docker-compose pull  # Récupère les nouvelles images Docker
+            docker-compose up -d  # Démarre les conteneurs en arrière-plan
