ResolveConflicts

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,6 +5,10 @@ on:
     branches:
       - main
 
+env:
+  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+
 jobs:
   merge_to_production:
     runs-on: ubuntu-latest
@@ -28,17 +32,16 @@ jobs:
           else
             git checkout -b production origin/production
           fi
-          
+
           git merge main --no-commit --no-ff  # Effectue la fusion sans commettre automatiquement
           git restore --staged .github/workflows/  # Réinitialise les workflows pour ne pas les inclure dans le commit
-          
+
           # Vérifier s'il y a des changements à commettre
           if git diff-index --quiet HEAD; then
             echo "Rien à commettre, l'arbre de travail est propre."
           else
             git commit -m "Merge main into production, excluding workflow changes"
             git push origin production  # Pousse la branche fusionnée
-          fi
 
   build_and_push_images:
     needs: merge_to_production
@@ -53,21 +56,25 @@ jobs:
 
       - name: Check Docker username
         run: |
-          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"  # Étape pour vérifier le nom d'utilisateur Docker
+          echo "Docker Username: ${{ env.DOCKER_USERNAME }}"  # Vérification du nom d'utilisateur Docker
 
       - name: Docker login to Docker Hub
         run: |
-          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+          echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build and push Backend (Spring Boot) Docker image
         run: |
-          docker build -t chirack96/springboot-app:latest ./dev
-          docker push chirack96/springboot-app:latest
+          docker build -t chirack96/springboot-app:latest ./dev || { echo "Docker build failed"; exit 1; }
+          docker push chirack96/springboot-app:latest || { echo "Docker push failed"; exit 1; }
 
       - name: Build and push Frontend (Angular) Docker image
         run: |
-          docker build -t chirack96/angular-app:latest ./Frontend
-          docker push chirack96/angular-app:latest
+          docker build -t chirack96/angular-app:latest ./Frontend || { echo "Docker build failed"; exit 1; }
+          docker push chirack96/angular-app:latest || { echo "Docker push failed"; exit 1; }
+
+      - name: Clean up Docker images
+        run: |
+          docker image prune -f
 
   deploy_to_server:
     needs: build_and_push_images
